/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HashTable */

#ifndef _Included_HashTable
#define _Included_HashTable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HashTable
 * Method:    ht_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_HashTable_ht_1new
  (JNIEnv *, jobject);

/*
 * Class:     HashTable
 * Method:    ht_insert
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_HashTable_ht_1insert
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     HashTable
 * Method:    ht_search
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_HashTable_ht_1search
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     HashTable
 * Method:    ht_delete
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_HashTable_ht_1delete
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     HashTable
 * Method:    ht_del_hash_table
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_HashTable_ht_1del_1hash_1table
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
