/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HashTable */

#ifndef _Included_HashTable
#define _Included_HashTable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HashTable
 * Method:    ht_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_HashTable_ht_1new
  (JNIEnv *, jobject);

/*
 * Class:     HashTable
 * Method:    get_size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_HashTable_get_1size
  (JNIEnv *, jobject, jlong);

/*
 * Class:     HashTable
 * Method:    ht_insert
 * Signature: (JCC)V
 */
JNIEXPORT void JNICALL Java_HashTable_ht_1insert
  (JNIEnv *, jobject, jlong, jchar, jchar);

/*
 * Class:     HashTable
 * Method:    ht_search
 * Signature: (JC)C
 */
JNIEXPORT jchar JNICALL Java_HashTable_ht_1search
  (JNIEnv *, jobject, jlong, jchar);

/*
 * Class:     HashTable
 * Method:    ht_delete
 * Signature: (JC)V
 */
JNIEXPORT void JNICALL Java_HashTable_ht_1delete
  (JNIEnv *, jobject, jlong, jchar);

#ifdef __cplusplus
}
#endif
#endif
